server:
  port: 8050
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: readshot2@gmail.com
    password: ayqqlaszwhqwadbp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/peaceSystemBuild?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:

custom:
  aligo:
    userId: readshot2
    apiKey: 7mg3f08mf9x67dbqty9mwvm9bth9pjri
  # director 등록신청시 업로드한 파일이 서버에 저장되는 경로 지정
  genFileDirPath: C:/work/peace
  logging:
    dir: log
    level: debug